# Generated by Django 5.1.1 on 2024-11-11 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_post_approved_alter_post_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': [('can_approve_posts', 'Can approve posts')]},
        ),
    ]
